##Question 1

##Statement

A computer center has three expert programmers. The center wants three application programs to be developed. The head of the computer center, after studying carefully the programmers to be deployed, estimates the computer time in minutes required by the experts for the application programmers as follows:

## Model

Minimize
$120x_{1} + 100x_{2} + 80x_{3} + 80y_{1} + 90y_{2} + 110y_{3} + 110z_{1} + 140z_{2} + 120z_{3}$

SUBJECT TO

$x_{1} + x_{2} + x_{3} = 1$

$y_{1} + y_{2} + y_{3} = 1$

$z_{1} + z_{2} + z_{3} = 1$

$x_{1} + y_{1} + z_{1} = 1$

$x_{2} + y_{2} + z_{2} = 1$

$x_{3} + y_{3} + z_{3} = 1$

$1>=x_{1} , x_{2} , x_{3}, y_{1} , y_{2} ,y_{3}, z_{1} , z_{2} , z_{3}>=0$

In [ ]:
!pip install pulp

     |████████████████████████████████| 40.6MB 102kB/s 


In [ ]:
from pulp import *
import numpy as np
import pandas as pd

In [ ]:
%ls

'Q1(data).csv'  'Q2(data).csv'   sample_data/


In [ ]:
df=pd.read_csv('Q1(data).csv')

In [ ]:
df.head()

A1   A2   A3
0  120  100   80
1   80   90  110
2  110  140  120

In [ ]:
nvar=9
ncons=6
cost=np.array([120,100,80,80,90,110,110,140,120])

Coff=np.array([[1,1,1,0,0,0,0,0,0],
               [0,0,0,1,1,1,0,0,0],
               [0,0,0,0,0,0,1,1,1],
               [1,0,0,1,0,0,1,0,0],
               [0,1,0,0,1,0,0,1,0],
               [0,0,1,0,0,1,0,0,1]])
   
resources=[1,1,1,1,1,1]      

In [ ]:
print(Coff)

[[1 1 1 0 0 0 0 0 0]
 [0 0 0 1 1 1 0 0 0]
 [0 0 0 0 0 0 1 1 1]
 [1 0 0 1 0 0 1 0 0]
 [0 1 0 0 1 0 0 1 0]
 [0 0 1 0 0 1 0 0 1]]


In [ ]:
#Define th model
model=LpProblem("LPP",LpMinimize)

#Define the decision variable
x = {i: LpVariable(name=f"x{i}", lowBound=0 , cat='Integer') for i in range(1,nvar+1)}

# Define The objective
model += lpSum(cost[i-1]*x[i] for i in range(1,nvar+1))


#Add Constraints

for j in range(ncons):
  model += lpSum(Coff[j,i-1]*x[i] for i in range(1,nvar+1))==resources[j]

#Print model
print(model)

# Solve the optimization problem
status = model.solve()

# Get the results
print('##############Solution of LPP is #################n\n')
print(f"status: {model.status}, {LpStatus[model.status]}")
print(f"objective: {model.objective.value()}")

for var in x.values():
  print(f"{var.name}: {var.value()}")

LPP:
MINIMIZE
120*x1 + 100*x2 + 80*x3 + 80*x4 + 90*x5 + 110*x6 + 110*x7 + 140*x8 + 120*x9 + 0
SUBJECT TO
_C1: x1 + x2 + x3 = 1

_C2: x4 + x5 + x6 = 1

_C3: x7 + x8 + x9 = 1

_C4: x1 + x4 + x7 = 1

_C5: x2 + x5 + x8 = 1

_C6: x3 + x6 + x9 = 1

VARIABLES
0 <= x1 Integer
0 <= x2 Integer
0 <= x3 Integer
0 <= x4 Integer
0 <= x5 Integer
0 <= x6 Integer
0 <= x7 Integer
0 <= x8 Integer
0 <= x9 Integer

##############Solution of LPP is #################n

status: 1, Optimal
objective: 280.0
x1: 0.0
x2: 0.0
x3: 1.0
x4: 0.0
x5: 1.0
x6: 0.0
x7: 1.0
x8: 0.0
x9: 0.0


In [ ]:
status = model.solve()
print(f"status: {model.status}, {LpStatus[model.status]}")
print(f"objective: {model.objective.value()}")

status: 1, Optimal
objective: 280.0


In [ ]:
for var in x.values():
    print(f"{var.name}: {var.value()}")

for var in y.values():
    print(f"{var.name}: {var.value()}")

for var in z.values():
    print(f"{var.name}: {var.value()}")

x1: 0.0
x2: 0.0
x3: 1.0
x4: 0.0
x5: 1.0
x6: 0.0
x7: 1.0
x8: 0.0
x9: 0.0
y1: 1.0
y2: 1.0
y3: 0.0
y4: 1.0
y5: 0.0
z1: 0.0
z2: 0.0
z3: 0.0
z4: 0.0
z5: 0.0


##Question 2

##Statement

A department has five employees with five jobs to be performed. The time (in hours) each men will take to perform each job is given in the effectiveness matrix

## Model

Minimize
$7u_{1} + 9u_{2} + 10u_{3} + 4u_{4} + 12u_{5} + 7w_{1} + 11w_{2} + 9w_{3} + 7w_{4} + 12w_{5} + 10x_{1} + 5x_{2} + 13x_{3} + 15x_{4} + 16x_{5} + 3y_{1} + 9y_{2} + 18y_{3} + 13y_{4} + 6y_{5} + 10z_{1} + 7z_{2} + 2z_{3} + 2z_{4} + 2z_{5}$

SUBJECT TO

$x_{1} + x_{2} + x_{3} + x_{4} + x_{5} = 1$

$y_{1} + y_{2} + y_{3} + y_{4} + y_{5} = 1$

$z_{1} + z_{2} + z_{3} + z_{4} + z_{5} = 1$

$w_{1} + w_{2} + w_{3} + w_{4} + w_{5} = 1$

$u_{1} + u_{2} + u_{3} + u_{4} + u_{5} = 1$

$u_{1} + w_{1} + x_{1} + y_{1} + z_{1} = 1$

$u_{2} + w_{2} + x_{2} + y_{2} + z_{2} = 1$

$u_{3} + w_{3} + x_{3} + y_{3} + z_{3} = 1$

$u_{4} + w_{4} + x_{4} + y_{4} + z_{4} = 1$

$u_{5} + w_{5} + x_{5} + y_{5} + z_{5} = 1$

$1>=x_{1},x_{2}, x_{3} , x_{4}  ,x_{5}, y_{1} , y_{2} , y_{3} , y_{4} , y_{5}, z_{1} , z_{2} , z_{3} , z_{4} , z_{5}, w_{1} , w_{2} , w_{3} , w_{4} , w_{5}, u_{1} , u_{2} , u_{3} , u_{4} , u_{5}>=0$


In [ ]:
%ls

'Q1(data).csv'  'Q2(data).csv'   sample_data/


In [ ]:
df=pd.read_csv('Q2(data).csv')

In [ ]:
df.head()

A1  A2  A3  A4  A5
0  10   5  13  15  16
1   3   9  18  13   6
2  10   7   2   2   2
3   7  11   9   7  12
4   7   9  10   4  12

In [ ]:

nvar=25
ncons=10
cost=np.array([10,5,13,15,16,3,9,18,13,6,10,7,2,2,2,7,11,9,7,12,7,9,10,4,12])

Coff=np.array([[1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
               [0,0,0,0,0,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
               [0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0],
               [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,0,0,0,0,0],
               [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1],
               [1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0],
               [0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0],
               [0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0],
               [0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0],
               [0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1]])

resources=[1,1,1,1,1,1,1,1,1,1]
        

In [ ]:
print(Coff)

[[1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1]
 [1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0]
 [0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0]
 [0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0]
 [0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0]
 [0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1]]


In [ ]:
#Define th model
model=LpProblem("LPP",LpMinimize)

#Define the decision variable
x = {i: LpVariable(name=f"x{i}", lowBound=0 , cat='Integer') for i in range(1,nvar+1)}

# Define The objective
model += lpSum(cost[i-1]*x[i] for i in range(1,nvar+1))


#Add Constraints

for j in range(ncons):
  model += lpSum(Coff[j,i-1]*x[i] for i in range(1,nvar+1))==resources[j]

#Print model
print(model)

# Solve the optimization problem
status = model.solve()

# Get the results
print('##############Solution of LPP is #################n\n')
print(f"status: {model.status}, {LpStatus[model.status]}")
print(f"objective: {model.objective.value()}")

for var in x.values():
  print(f"{var.name}: {var.value()}")

LPP:
MINIMIZE
10*x1 + 6*x10 + 10*x11 + 7*x12 + 2*x13 + 2*x14 + 2*x15 + 7*x16 + 11*x17 + 9*x18 + 7*x19 + 5*x2 + 12*x20 + 7*x21 + 9*x22 + 10*x23 + 4*x24 + 12*x25 + 13*x3 + 15*x4 + 16*x5 + 3*x6 + 9*x7 + 18*x8 + 13*x9 + 0
SUBJECT TO
_C1: x1 + x2 + x3 + x4 + x5 = 1

_C2: x10 + x6 + x7 + x8 + x9 = 1

_C3: x11 + x12 + x13 + x14 + x15 = 1

_C4: x16 + x17 + x18 + x19 + x20 = 1

_C5: x21 + x22 + x23 + x24 + x25 = 1

_C6: x1 + x11 + x16 + x21 + x6 = 1

_C7: x12 + x17 + x2 + x22 + x7 = 1

_C8: x13 + x18 + x23 + x3 + x8 = 1

_C9: x14 + x19 + x24 + x4 + x9 = 1

_C10: x10 + x15 + x20 + x25 + x5 = 1

VARIABLES
0 <= x1 Integer
0 <= x10 Integer
0 <= x11 Integer
0 <= x12 Integer
0 <= x13 Integer
0 <= x14 Integer
0 <= x15 Integer
0 <= x16 Integer
0 <= x17 Integer
0 <= x18 Integer
0 <= x19 Integer
0 <= x2 Integer
0 <= x20 Integer
0 <= x21 Integer
0 <= x22 Integer
0 <= x23 Integer
0 <= x24 Integer
0 <= x25 Integer
0 <= x3 Integer
0 <= x4 Integer
0 <= x5 Integer
0 <= x6 Integer
0 <= x7 Integer
0 <= x8 Intege

In [ ]:
status = model.solve()
print(f"status: {model.status}, {LpStatus[model.status]}")
print(f"objective: {model.objective.value()}")

status: 1, Optimal
objective: 23.0


In [ ]:
for var in x.values():
    print(f"{var.name}: {var.value()}")

for var in y.values():
    print(f"{var.name}: {var.value()}")

for var in z.values():
    print(f"{var.name}: {var.value()}")
for var in p.values():
    print(f"{var.name}: {var.value()}")
for var in q.values():
    print(f"{var.name}: {var.value()}")        

x1: 0.0
x2: 1.0
x3: 0.0
x4: 0.0
x5: 0.0
x6: 1.0
x7: 0.0
x8: 0.0
x9: 0.0
x10: 0.0
x11: 0.0
x12: 0.0
x13: 0.0
x14: 0.0
x15: 1.0
x16: 0.0
x17: 0.0
x18: 1.0
x19: 0.0
x20: 0.0
x21: 0.0
x22: 0.0
x23: 0.0
x24: 1.0
x25: 0.0
y1: 0.0
y2: 0.0
y3: 0.0
y4: 0.0
y5: 0.0
z1: 1.0
z2: 0.0
z3: 0.0
z4: 1.0
z5: 1.0
p1: 0.0
p2: 0.0
p3: 0.0
p4: 0.0
p5: 0.0
q1: 0.0
q2: 0.0
q3: 1.0
q4: 0.0
q5: 0.0
