##Question 1.

#Model
Maximize $Z=8x_{1}+9 x_{2}+7x_{3}+6 x_{4}$

subject to

$0.5x_{1}+x_{2}+x_{3}+0.5x_{4}<=1800$

$2x_{1}+x_{2}+x_{3}+x_{4}<=2800$

$0.5x_{1}+0.5x_{2}+x_{3}+x_{4}<=3000$

$3x_{1}+x_{2}+2x_{3}+3x_{4}<=6000$

$-x_{1}+0x_{2}+0x_{3}+0x_{4}<=-100$

$0x_{1}+-x_{2}+0x_{3}+0x_{4}<=-600$

$0x_{1}+0x_{2}+-x_{3}+0x_{4}<=-500$

$0x_{1}+0x_{2}+0x_{3}+-x_{4}<=-400$


##LPP MODEL BY READING DATA FROM FILE

###Implementations

In [ ]:
!pip install pulp

     |████████████████████████████████| 40.6MB 102kB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
  Created wheel for amply: filename=amply-0.1.2-cp36-none-any.whl size=16573 sha256=b80402a109ef679a4fbb6909c305954aad7cae48ad77b921a4b9649e19a03703
  Stored in directory: /root/.cache/pip/wheels/84/18/f7/e5c3ed13ed5bb721763f77d4a924331d59ef115ce61c9d26eb
Successfully built amply


In [ ]:
from pulp import *
import numpy as np
import pandas as pd



In [ ]:
%ls

Q1.csv  Q2.csv  Q3.csv  sample_data/


In [ ]:
df=pd.read_csv('Q1.csv')

In [ ]:
df.head(8)

A1   A2  A3   A4  Cost  Resource
0  0.5  1.0   1  0.5   8.0      1800
1  2.0  1.0   1  1.0   9.0      2800
2  0.5  0.5   1  1.0   7.0      3000
3  3.0  1.0   2  3.0   6.0      6000
4 -1.0  0.0   0  0.0   NaN      -100
5  0.0 -1.0   0  0.0   NaN      -600
6  0.0  0.0  -1  0.0   NaN      -500
7  0.0  0.0   0 -1.0   NaN      -400

## Define Data

In [ ]:
nvar=4
ncons=8
cost=df['Cost'].to_numpy()

Coff=df.iloc[0:8,0:8].to_numpy()
               

resources=list(df['Resource'].iloc[0:8])

In [ ]:
resources

[1800, 2800, 3000, 6000, -100, -600, -500, -400]

In [ ]:
Coff

array([[ 5.0e-01,  1.0e+00,  1.0e+00,  5.0e-01,  8.0e+00,  1.8e+03],
       [ 2.0e+00,  1.0e+00,  1.0e+00,  1.0e+00,  9.0e+00,  2.8e+03],
       [ 5.0e-01,  5.0e-01,  1.0e+00,  1.0e+00,  7.0e+00,  3.0e+03],
       [ 3.0e+00,  1.0e+00,  2.0e+00,  3.0e+00,  6.0e+00,  6.0e+03],
       [-1.0e+00,  0.0e+00,  0.0e+00,  0.0e+00,      nan, -1.0e+02],
       [ 0.0e+00, -1.0e+00,  0.0e+00,  0.0e+00,      nan, -6.0e+02],
       [ 0.0e+00,  0.0e+00, -1.0e+00,  0.0e+00,      nan, -5.0e+02],
       [ 0.0e+00,  0.0e+00,  0.0e+00, -1.0e+00,      nan, -4.0e+02]])

In [ ]:

# Define the model
model = LpProblem("LPP",LpMaximize)


# Define the decision variables
x = {i: LpVariable(name=f"x{i}", lowBound=0) for i in range(1, nvar+1)}


# Set the objective
model+=lpSum(cost[i-1]*x[i] for i in range(1,nvar+1))


# Add constraints

for j in range(ncons):
  model += lpSum(Coff[j,i-1]*x[i] for i in range(1,nvar+1))<=resources[j]

# Print Model
print(model)


# Solve the optimization problem
status = model.solve()

# Get the results
print('##############Solution of LPP is ##################\n\n')
print(f"status: {model.status}, {LpStatus[model.status]}")
print(f"objective: {model.objective.value()}")

for var in x.values():
    print(f"{var.name}: {var.value()}")


LPP:
MAXIMIZE
8.0*x1 + 9.0*x2 + 7.0*x3 + 6.0*x4 + 0.0
SUBJECT TO
_C1: 0.5 x1 + x2 + x3 + 0.5 x4 <= 1800

_C2: 2 x1 + x2 + x3 + x4 <= 2800

_C3: 0.5 x1 + 0.5 x2 + x3 + x4 <= 3000

_C4: 3 x1 + x2 + 2 x3 + 3 x4 <= 6000

_C5: - x1 <= -100

_C6: - x2 <= -600

_C7: - x3 <= -500

_C8: - x4 <= -400

VARIABLES
x1 Continuous
x2 Continuous
x3 Continuous
x4 Continuous

##############Solution of LPP is ##################


status: 1, Optimal
objective: 17900.0
x1: 300.0
x2: 600.0
x3: 500.0
x4: 1100.0


##Question 2.

Minimize Z = 8x_1+4x_2  +2 x_3 

Subject to

4x_1+2x_2  + x_3  ≤8

3x_1+2x_2   ≤10

-x_1 - x_2  - x_3  >= -4

x_1>=0,x_2>=0,x_3>= 0


##LPP MODEL BY READING DATA FROM FILE

###Implementation

In [ ]:
%ls

Q1.csv  Q2.csv  sample_data/


In [ ]:
df=pd.read_csv('Q2.csv')

In [ ]:
df.head()

A1  A2  A3  Cost  Resource
0   4   2   1     8         8
1   3   2   0     4        10
2  -1  -1  -1     2        -4

##Definig Data

In [ ]:
nvar=3
ncons=3
cost=df['Cost'].to_numpy()

Coff=df.iloc[0:3,:3].to_numpy()
               

resources=list(df['Resource'].iloc[0:3])

In [ ]:
cost

array([8, 4, 2])

In [ ]:
resources

[8, 10, -4]

In [ ]:
Coff

array([[ 4,  2,  1],
       [ 3,  2,  0],
       [-1, -1, -1]])

In [ ]:

# Define the model
model = LpProblem("LPP",LpMinimize)


# Define the decision variables
x = {i: LpVariable(name=f"x{i}", lowBound=0) for i in range(1, nvar+1)}


# Set the objective
model+=lpSum(cost[i-1]*x[i] for i in range(1,nvar+1))


# Add constraints

for j in range(ncons):
  model += lpSum(Coff[j,i-1]*x[i] for i in range(1,nvar+1))<=resources[j]

# Print Model
print(model)


# Solve the optimization problem
status = model.solve()

# Get the results
print('##############Solution of LPP is ##################\n\n')
print(f"status: {model.status}, {LpStatus[model.status]}")
print(f"objective: {model.objective.value()}")

for var in x.values():
    print(f"{var.name}: {var.value()}")


LPP:
MINIMIZE
8*x1 + 4*x2 + 2*x3 + 0
SUBJECT TO
_C1: 4 x1 + 2 x2 + x3 <= 8

_C2: 3 x1 + 2 x2 <= 10

_C3: - x1 - x2 - x3 <= -4

VARIABLES
x1 Continuous
x2 Continuous
x3 Continuous

##############Solution of LPP is ##################


status: 1, Optimal
objective: 8.0
x1: 0.0
x2: 0.0
x3: 4.0


##Question

##Maximize Z = 5x_1- 2x_2  +3 x_3 

Subject to

2x_1+1x_2  - 6x_3=20

8x_1- 3x_2  + 6x_3+x_4  ≤50

6x_1+5 x_2  + 10x_3+x_4  <=76

x_1>=0,x_2>=0,x_3>= 0


##LPP MODEL BY READING DATA FROM FILE

##Implementation

In [ ]:
%ls


Q1.csv  Q2.csv  Q3.csv  sample_data/


In [ ]:
df=pd.read_csv('Q3.csv')

In [ ]:
df.head()

A1  A2  A3  A4  Cost  Resource
0   2   1  -6   0     5        20
1  -2  -1   6   0    -2       -20
2   8  -3   6   1     3        50
3   6   5  10   1     0        76

###Definig Data

In [ ]:
nvar=4
ncons=4
cost=df['Cost'].to_numpy()

Coff=df.iloc[0:4,:4].to_numpy()
               

resources=list(df['Resource'].iloc[0:4])

In [ ]:

# Define the model
model = LpProblem("LPP",LpMaximize)


# Define the decision variables
x = {i: LpVariable(name=f"x{i}", lowBound=0) for i in range(1, nvar+1)}


# Set the objective
model+=lpSum(cost[i-1]*x[i] for i in range(1,nvar+1))


# Add constraints

for j in range(ncons):
  model += lpSum(Coff[j,i-1]*x[i] for i in range(1,nvar+1))<=resources[j]

# Print Model
print(model)


# Solve the optimization problem
status = model.solve()

# Get the results
print('##############Solution of LPP is ##################\n\n')
print(f"status: {model.status}, {LpStatus[model.status]}")
print(f"objective: {round(model.objective.value(),2)}")

for var in x.values():
    print(f"{var.name}: {round(var.value(),2)}")


LPP:
MAXIMIZE
5*x1 + -2*x2 + 3*x3 + 0
SUBJECT TO
_C1: 2 x1 + x2 - 6 x3 <= 20

_C2: - 2 x1 - x2 + 6 x3 <= -20

_C3: 8 x1 - 3 x2 + 6 x3 + x4 <= 50

_C4: 6 x1 + 5 x2 + 10 x3 + x4 <= 76

VARIABLES
x1 Continuous
x2 Continuous
x3 Continuous
x4 Continuous

##############Solution of LPP is ##################


status: 1, Optimal
objective: 30.71
x1: 7.86
x2: 4.29
x3: 0.0
x4: 0.0
